# Generated by Django 4.0.5 on 2022-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='字段类型', max_length=100, verbose_name='字段类型')),
            ],
            options={
                'verbose_name': '字段类型',
                'verbose_name_plural': '字段类型',
                'db_table': 'config_column_type',
            },
        ),
        migrations.CreateModel(
            name='GenerateTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='插入类型', max_length=100, verbose_name='插入类型')),
            ],
            options={
                'verbose_name': '生成类型',
                'verbose_name_plural': '生成类型',
                'db_table': 'config_generate_type',
            },
        ),
        migrations.CreateModel(
            name='TableContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_code', models.CharField(help_text='字段类型', max_length=100, verbose_name='编码')),
                ('arg_name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('value_generate', models.CharField(help_text='值生成器', max_length=100, verbose_name='值生成器')),
            ],
            options={
                'verbose_name': '表上下文',
                'verbose_name_plural': '表上下文',
                'db_table': 'config_table_content',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务状态', max_length=100, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务状态',
                'verbose_name_plural': '任务状态',
                'db_table': 'config_task_status',
            },
        ),
    ]
