# Generated by Django 4.0.5 on 2022-06-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='规则名称', max_length=100, verbose_name='规则名称')),
                ('role_detail', models.CharField(help_text='规则', max_length=100, verbose_name='规则')),
            ],
            options={
                'verbose_name': '字段类型',
                'verbose_name_plural': '字段类型',
                'db_table': 'config_role',
            },
        ),
        migrations.AddField(
            model_name='columntypemodel',
            name='role',
            field=models.ForeignKey(blank=True, default=None, help_text='规则', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.rolesmodel', verbose_name='规则'),
        ),
    ]
