# Generated by Django 4.0.5 on 2022-06-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_rolesmodel_columntypemodel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesmodel',
            options={'verbose_name': '字段规则', 'verbose_name_plural': '字段规则'},
        ),
        migrations.RemoveField(
            model_name='columntypemodel',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolesmodel',
            name='role_detail',
        ),
        migrations.AddField(
            model_name='rolesmodel',
            name='role',
            field=models.ForeignKey(blank=True, default=None, help_text='规则', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_column', to='config.columntypemodel', verbose_name='规则'),
        ),
    ]
