# Generated by Django 4.0.5 on 2022-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_rolesmodel_options_remove_columntypemodel_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据库类型')),
            ],
            options={
                'verbose_name': '字段类型',
                'verbose_name_plural': '字段类型',
                'db_table': 'config_db_type',
            },
        ),
    ]
