# Generated by Django 4.0.5 on 2022-06-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_sql', models.TextField(help_text='插入前sql', verbose_name='插入前sql')),
                ('post_sql', models.TextField(help_text='插入的sql语句', verbose_name='插入的sql语句')),
                ('upper_nums', models.IntegerField(help_text='随机插入上限', verbose_name='随机插入上限')),
                ('lower_nums', models.IntegerField(help_text='随机插入下限', verbose_name='随机插入下限')),
                ('generate_type', models.ForeignKey(help_text='插入类型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g_task', to='config.generatetypemodel', verbose_name='插入类型')),
                ('status', models.ForeignKey(help_text='任务状态', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ts_task', to='config.taskstatusmodel', verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '字段',
                'verbose_name_plural': '字段',
                'db_table': 'task_task',
            },
        ),
    ]
