# Generated by Django 4.0.5 on 2022-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': '任务配置', 'verbose_name_plural': '任务配置'},
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='lower_nums',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='upper_nums',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='插入前sql', max_length=300, null=True, verbose_name='插入前sql'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='nums',
            field=models.IntegerField(default=1, help_text='随机插入上限', verbose_name='插入'),
        ),
    ]
