# Generated by Django 4.0.5 on 2022-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_options_remove_taskmodel_lower_nums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='nums',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='任务名称', max_length=300, null=True, verbose_name='任务名称'),
        ),
    ]
