# Generated by Django 4.0.5 on 2022-06-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='parent_business_id',
            field=models.ForeignKey(default=None, help_text='父业务', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_business', to='business.business', verbose_name='父业务'),
        ),
    ]
