# Generated by Django 4.0.5 on 2022-06-29 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_parent_business_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '业务配置', 'verbose_name_plural': '业务配置'},
        ),
        migrations.AlterField(
            model_name='business',
            name='parent_business_id',
            field=models.ForeignKey(blank=True, default=None, help_text='父业务', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_business', to='business.business', verbose_name='父业务'),
        ),
        migrations.CreateModel(
            name='BusinessWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('num', models.IntegerField(help_text='执行次数', verbose_name='执行次数')),
                ('business', models.ManyToManyField(blank=True, default=None, help_text='包含业务', null=True, related_name='b_business_work', to='business.business', verbose_name='包含业务')),
            ],
            options={
                'verbose_name': '工作配置',
                'verbose_name_plural': '工作配置',
                'db_table': 'business_work',
            },
        ),
    ]
