# Generated by Django 4.0.5 on 2022-06-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projectmodel_version_versionmodel_project'),
        ('business', '0003_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_business', to='project.versionmodel', verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='businesswork',
            name='version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_business_work', to='project.versionmodel', verbose_name='版本'),
        ),
    ]
