# Generated by Django 4.0.5 on 2022-06-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='表名', max_length=100, verbose_name='表名')),
                ('raw_table_name', models.CharField(help_text='原库中表名', max_length=100, verbose_name='原库中表名')),
                ('parent_table_id', models.ForeignKey(help_text='父级表', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_table', to='tables.table', verbose_name='父级表')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_table', to='project.versionmodel', verbose_name='版本')),
            ],
            options={
                'verbose_name': '表',
                'verbose_name_plural': '表',
                'db_table': 'table_table',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='字段名', max_length=100, verbose_name='字段名')),
                ('raw_column_name', models.CharField(help_text='原表中字段名', max_length=100, verbose_name='原表中字段名')),
                ('type', models.ForeignKey(help_text='字段类型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_type', to='config.columntypemodel', verbose_name='字段类型')),
            ],
            options={
                'verbose_name': '字段',
                'verbose_name_plural': '字段',
                'db_table': 'table_column',
            },
        ),
    ]
