# Generated by Django 4.0.5 on 2022-06-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_column_type_alter_table_parent_table_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(blank=True, default=None, help_text='表', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_column', to='tables.table', verbose_name='表'),
        ),
        migrations.AlterField(
            model_name='table',
            name='parent_table_id',
            field=models.ForeignKey(blank=True, default=None, help_text='父级表', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t_table', to='tables.table', verbose_name='父级表'),
        ),
    ]
