# Generated by Django 4.0.5 on 2022-06-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_column_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='version',
        ),
    ]
