# Generated by Django 4.0.5 on 2022-06-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='version',
        ),
        migrations.AddField(
            model_name='versionmodel',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_project', to='project.projectmodel', verbose_name='版本'),
        ),
    ]
