# Generated by Django 4.0.5 on 2022-06-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlmodel',
            options={'verbose_name': '历史记录', 'verbose_name_plural': '历史记录'},
        ),
    ]
